### ISSUE TITLE
F5 keymap

### ISSUE THREAD

**Issue by eltoro** [kiddkai/atom-node-debugger#100]
I have a fairly new MacBook Pro and when I hit the F5 to start the debugger it's ignored. It triggers the backlight brightness. Is there a way to fix this?

**Comment by codecontemplator** [comment]
Have you set the path to node?

**Comment by eltoro** [comment]
Yep.

**Comment by rajorator** [comment]
Type fn + F5 to start the debugger.

**Comment by eltoro** [comment]
That did it. Thanks.
