### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by seriousme** [kiddkai/atom-node-debugger#101]
Hi,

I have been playing around with the debugger and I have a few suggestions:
a) add an item to the Packages menu (I noticed that menus/node-debugger.cson had been emptied :-() so that the F5 etc can be learned from a menu.
b) make it possible to close the debugging window (for now the only option seems to be to restart atom)

Happy to give it a try myself and send in a PR , but if people think its the wrong way round I would be wasting my time ;-)

Cheers,
Hans

**Comment by codecontemplator** [comment]
Hi!

You can press shift+F5 to close the debugger windows. 

Adding the commands to the menu would be a good thing imo. 

Cheers

**Comment by codecontemplator** [comment]
I added in the menu items as suggested. Thanks

https://github.com/kiddkai/atom-node-debugger/pull/107

**Comment by seriousme** [comment]
Great, thanks for the hint and for submitting the PR !
btw: one of the menu items is named "Stop Out" instead of "Step Out".

You might also want to add the keys to the labels  e.g.:
 ``` 'label': 'Start/Resume (F5)' ```

So people know there are shortcut keys ;-)

**Comment by codecontemplator** [comment]
Thanks for point that out. :)

It seems like atom does add the shortcuts automagically (at least on windows and ubuntu):

![image](https://cloud.githubusercontent.com/assets/3386085/11429115/ae9acbf6-9473-11e5-804b-2aba70affbf1.png)

**Comment by seriousme** [comment]
Brilliant ! (didn't know that ;-))

Thanks again,
Hans
