### ISSUE TITLE
ability to set environment vars when launching debugger

### ISSUE THREAD

**Issue by DarthGoon** [kiddkai/atom-node-debugger#104]
The `env` config var that is in this github documentation- doesn't seem to be available in the module settings.
![image](https://cloud.githubusercontent.com/assets/719791/11406717/d7508e34-937c-11e5-990b-22a2bdb790ca.png)

**Comment by DarthGoon** [comment]
nevermind.  i just realized the code is not part of 1.1.9

**Comment by codecontemplator** [comment]
Should be in the new release now.

**Comment by DarthGoon** [comment]
@codecontemplator Atom just beat webstorm as my IDE for node on osx.  Thanks for the release, man- very much appreciated :+1: :confetti_ball: :beers:
