### ISSUE TITLE
New release: v.1.1.11

### ISSUE THREAD

**Issue by codecontemplator** [kiddkai/atom-node-debugger#106]
Hey @kiddkai,

Since it was a while ago since a new release was built I tried to make one (or two actually). Hope that was ok. Are you in a position to assist a little bit? I do not think I have permission to publish the new release to atom.io or I might be doing something wrong.

Thanks for your help

**Comment by codecontemplator** [comment]
After doing some research I realize I might have been better of using apm publish in some way. Hope I did not create a mess.

**Comment by kiddkai** [comment]
Hey, Daniel

Sorry for the late reply, just having a travel in Melbourne this week. I
think you can try publish it, if you can't, I don't know if apm have the
same feature as npm that allow adding new people to the project. If it's
not, I can send you the key I generate from atom.io to you

**Comment by kiddkai** [comment]
Do you have Facebook message or whapsapp or some instant message app you have that I can send you tokens if it fail to publish?

**Comment by codecontemplator** [comment]
I got it working but I sent you a link to my fb profile anyway. Made a misstake on the versioning numbering so it ended up at 1.3 instead of 1.2.1. Sorry about that. Think it is hard to change unfortunately. Enjoy your time in Melbourne. :)
