### ISSUE TITLE
Line wraps for long breakpoint/call stack/local vars

### ISSUE THREAD

**Issue by reinvantveer** [kiddkai/atom-node-debugger#109]
Perhaps this is more a question than an issue: how do I get node-debugger to wrap info around? Half of my data in the breakpoints/call stack etc. window pane is not visible.

Thanks in advance

**Comment by codecontemplator** [comment]
Hi,

Thanks for the feedback. Is it possible to attach  a screenshot?

**Comment by reinvantveer** [comment]
Sure.
![screenshot from 2015-11-26 12 40 53](https://cloud.githubusercontent.com/assets/9550733/11423298/110525ae-943b-11e5-9d6f-4e5d325dbc95.png)

**Comment by reinvantveer** [comment]
By the way, I can't pull the pane to the left. I can only pull it to the right to make it smaller, but that doesn't help much :feelsgood:

**Comment by codecontemplator** [comment]
The resizing problem has been addressed in https://github.com/kiddkai/atom-node-debugger/pull/110

**Comment by codecontemplator** [comment]
Pull request #120 saves screen space by only displaying project relative paths.

**Comment by codecontemplator** [comment]
Think this is solved now.
