### ISSUE TITLE
Uncaught MainLoopInvalidUpdateInRenderError: main-loop: Unexpected update occurred in loop.We ar...

### ISSUE THREAD

**Issue by Alaneor** [kiddkai/atom-node-debugger#112]
Hello, I am getting this error immediately after starting a new debugging session. Absolutely no idea what is going on. :)

**Atom Version**: 1.3.0-beta6
**System**: Mac OS X 10.11.1
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.3.0

### Stack Trace

Uncaught MainLoopInvalidUpdateInRenderError: main-loop: Unexpected update occurred in loop.
We are currently rendering a view, you can't change state right now.
The diff is: {"breakpoints":{"loading":true}}.
SUGGESTED FIX: find the state mutation in your view or rendering function and remove it.
The view should not have any side effects.

```
At /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/index.js:43

MainLoopInvalidUpdateInRenderError: main-loop: Unexpected update occurred in loop.
We are currently rendering a view, you can't change state right now.
The diff is: {"breakpoints":{"loading":true}}.
SUGGESTED FIX: find the state mutation in your view or rendering function and remove it.
The view should not have any side effects.

    at createError (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/node_modules/error/typed.js:31:22)
    at update (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/index.js:43:19)
    at /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ/index.js:10:13
    at Array.forEach (native)
    at Observable.observable.set (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ/index.js:9:19)
    at Function.trackDiff [as set] (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ-struct/index.js:77:20)
    at /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ-struct/index.js:69:21
    at /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ/index.js:10:13
    at Array.forEach (native)
    at Observable.observable.set (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ/index.js:9:19)
    at Function.trackDiff [as set] (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ-struct/index.js:77:20)
    at /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ-struct/index.js:69:21
    at /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ/index.js:10:13
    at Array.forEach (native)
    at Function.Observable.observable.set (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/observ/index.js:9:19)
    at Function.TreeView.populate (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/lib/Components/TreeView.coffee:46:17)
    at Array.refresh (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/lib/Components/BreakPointPane.coffee:33:30)
    at Object.broadcast (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/geval/event.js:10:25)
    at Client.<anonymous> (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/lib/debugger.coffee:299:48)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at Client._onResponse (_debugger.js:221:10)
    at Protocol.execute (_debugger.js:120:14)
    at Protocol._newRes (_debugger.js:74:8)
    at Protocol.execute (_debugger.js:122:14)
    at Client.<anonymous> (_debugger.js:159:14)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Client.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
  2x -3:13.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:12.9.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -3:12.7.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -2:43.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
  2x -0:34.2.0 sort-lines:sort (atom-text-editor.editor.is-focused)
  6x -0:26.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:25.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:21.6.0 node-debugger:step-next (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.6.0 node-debugger:stop (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:04.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 node-debugger:start-resume (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "turbo-javascript",
      "lcov-info",
      "atom-material-ui",
      "git-history",
      "minimap-linter",
      "sloc",
      "api-blueprint-preview"
    ],
    "disabledPackages": [
      "language-javascript",
      "git-control",
      "api-blueprint-preview"
    ],
    "projectHome": "/Users/BeBe/Dropbox/Repositories"
  },
  "node-debugger": {
    "nodePath": "/usr/local/bin/node"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-chai-snippets, v0.3.0
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
atom-pair, v2.0.10
autocomplete-modules, v1.3.1
build, v0.49.2
docblockr, v0.7.3
editor-stats, v0.17.0
editorconfig, v1.2.2
file-icons, v1.6.12
git-log, v0.4.1
highlight-selected, v0.11.1
language-api-blueprint, v1.0.2
language-babel, v2.5.2
language-gitignore, v0.2.0
language-ini, v1.14.0
language-jade, v0.6.2
linter, v1.11.2
linter-eslint, v5.2.4
minimap, v4.16.2
minimap-git-diff, v4.1.8
node-debugger, v1.3.0
project-manager, v2.6.5
sort-lines, v0.12.0
terminal-plus, v0.14.5
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
Hmmm. That does not look right indeed.

Mercury says that that view-model state was mutated during rendering. Judging from the callstack I cannot see the problem though. I had a theory that the asynchronous loading could be causing the problem but from this thread:

https://github.com/Raynos/main-loop/issues/11

it seems like another error (raised during rendering) could cause this problem. Would you mind pressing ctrl+alt+i (or whatever shortcut is used on mac) to launch the internal atom debugger and then start the debugger and see if any error is logged in the console?

**Comment by Alaneor** [comment]
Actually there are! When toggling the debugger view, I get three consecutive errors.

As I was unable to find better way of copying the stack traces in full and in readable format, I'll just go with good ol' screenshot.

> Note that I am using Atom Beta 1.3, if that makes any difference...

The first error appears here: */Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/node_modules/raf/index.js*
![screen shot 2015-11-27 at 23 02 17](https://cloud.githubusercontent.com/assets/3058150/11448599/bae0dd90-955b-11e5-9ba1-5ba1a78ca093.png)

Second one here: */Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/index.js*
![screen shot 2015-11-27 at 23 02 40](https://cloud.githubusercontent.com/assets/3058150/11448607/e836c87c-955b-11e5-88ac-14b4556f7cc9.png)

Third one here: */Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/index.js*
![screen shot 2015-11-27 at 23 02 53](https://cloud.githubusercontent.com/assets/3058150/11448612/f9b08156-955b-11e5-997e-269ef1e7f4bd.png)

**Comment by Alaneor** [comment]
**Update:** Remembered I can just click on *Report this issue* when the error occurs. :) Here are the details for the first error, as that's probably the root cause of this whole thing.

```
At /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/node_modules/raf/index.js:74

TypeError: Cannot read property 'tokenizeLine' of undefined
    at tokenizeLine (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/lib/Components/ConsolePane.coffee:13:25)
    at Array.map (native)
    at Function.ConsolePane.render (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/lib/Components/ConsolePane.coffee:130:22)
    at LeftSidePane (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/lib/Components/App.coffee:23:17)
    at App.render (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/lib/Components/App.coffee:146:9)
    at redraw (/Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/index.js:65:23)
    at /Users/BeBe/Dropbox/System/Atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/node_modules/raf/index.js:72:10
```

### Commands

```
     -0:15.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:08.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 node-debugger:start-resume (atom-text-editor.editor)

**Comment by codecontemplator** [comment]
Thanks! That was very useful. 

The node debugger tries to make som nice formatting of the output in the console window. For that it retrieves the grammar for .js files using

```coffeescript
atom.grammars.grammarForScopeName('source.js')
```

In your case it seems to return undefined which is not handled by the node-debugger source code which seems to be the reason for the error. If you want you can confirm this by executing the above codeline from the console shell in atom:
 
![image](https://cloud.githubusercontent.com/assets/3386085/11459313/f6028c42-96d3-11e5-968c-cee0d7382506.png)

In my case I get a grammar back but I suspect you do not for some reason. Do you have a custom grammar file installed?

**Comment by Alaneor** [comment]
That's most likely the case - I use the [language-babel](https://atom.io/packages/language-babel) Atom package for ES2015 syntax support (although I only use syntax already present in latest Node.js release).

I am currently not at my PC so I cannot test that command, I will do it first thing in the morning and let you know what the result is.

**Comment by Alaneor** [comment]
Just tested. It indeed returned `undefined`.

I realised that I had disabled the `language-javascript` package as I only use the Babel-provided syntax. Enabling this package fixed this error!

I am unsure if you would like to somehow handle such situations, but right now I consider my issue solved. :)

**Comment by codecontemplator** [comment]
That's great. Thanks for hunting this down. I suggest we keep this open. A proper fallback should be implemented if the js grammar is not available. Should be quite straightforward to implement I think.

**Comment by codecontemplator** [comment]
Fixed
