### ISSUE TITLE
Need a prompt of unsaved files

### ISSUE THREAD

**Issue by chentydev** [kiddkai/atom-node-debugger#115]
I'm using the debugger in OS X. 
If I have made some changes to my code, and then start debugging before saving the file, it will not remind me to save the changes first. Instead, the debugger just ignores the changes and works on the previously saved version. This looks really weird because the code  you are looking at is NOT the same copy used for debugging. 
Most IDEs will ask you to save the code before debugging. I believe that's what needed for this debugger.

**Comment by codecontemplator** [comment]
Yes that makes perfect sense. Thanks for your feedback.

**Comment by codecontemplator** [comment]
Visual studio auto saves modifies files without asking any questions first so this behaviour was implemented.
