### ISSUE TITLE
Debugger not hitting break points

### ISSUE THREAD

**Issue by kawalgrover** [kiddkai/atom-node-debugger#117]
Hi,

I tried to run node-debugger on Atom IDE (I'm new to both of them) and couldn't get the debugger to run.

I followed the simple instructions on your readme file.

Basically when I set the breakpoints, the color in the gutter is not red but orange.

My atom config file looks like this:

"*":
  "exception-reporting":
    userId: "d83708f6-5930-7517-b26b-0c308db6ab8e"
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}

  "node-debugger":
    nodePath: "/usr/local/bin"
    nodeArgs: "--use-strict --use_inlining"
    appArgs: "--arg1=10 --arg2"
    debugPort: 5860
    env: ""

<img width="1666" alt="screen shot 2015-12-07 at 9 26 05 pm" src="https://cloud.githubusercontent.com/assets/3866129/11669222/92c8f930-9e36-11e5-9556-b47f76148ac5.png">

**Comment by codecontemplator** [comment]
Hi,
The settings given on the docs page are just samples. It might be enough to remove them. If that does not work try setting the nodePath to point to your node install directory.

**Comment by kawalgrover** [comment]
> It might be enough to remove them.  If that does not work try setting the
nodePath to point to your node install

This worked! Thank you SO MUCH! Apparently the nodePath was not accurate.



On Thu, Dec 10, 2015 at 9:15 PM, Daniel Brännström <notifications@github.com

**Comment by codecontemplator** [comment]
Happy debugging :) cheers!
