### ISSUE TITLE
Ability to watch a selected variable

### ISSUE THREAD

**Issue by caglarcem** [kiddkai/atom-node-debugger#124]
Hi there, sorry if this feature already exists, i couldn't find how to do it although i had a good look.

Can we watch a variable by its name during debugging?

**Comment by codecontemplator** [comment]
Hi,
You may use the input box. Moreover you may watch local variables in the current frame, using the locals view, or any frame in the call stack view.  There is currently no 'custom watch' though which  a presume you ask for. Would be a nice feature though.

**Comment by yalishizhude** [comment]
@codecontemplator 
I can't fully understand you.Would you please give us a screen shot?

**Comment by yalishizhude** [comment]
When can we have the important feature  'custom watch'  ? @codecontemplator

**Comment by codecontemplator** [comment]
I have done some work on it. Cannot promise anything though. It is only something I do on my spare time. Thanks for writing though. Keeps me motivated to continue.

**Comment by yalishizhude** [comment]
Thanks very much, we are looking forward to that~
It is a great pity without "watch expression" feature for the most popular node.js debug tool of atom.

**Comment by codecontemplator** [comment]
Implemented in the latest release. A bit rough around the edges but I think it is better than nothing..
