### ISSUE TITLE
Can you allow us to debug a currently running instance that is already debugging?

### ISSUE THREAD

**Issue by intervalia** [kiddkai/atom-node-debugger#125]
At work I have a complicated startup process for my node apps. I can't just have your debugger start my app. I need to be able to have your debugger attach itself to an already running instance of a node app.

Can this be done?
Mike

**Comment by akoskm** [comment]
duplicate of https://github.com/kiddkai/atom-node-debugger/issues/23

**Comment by codecontemplator** [comment]
Duplicate of #23
