### ISSUE TITLE
Configuration problem: appArgs

### ISSUE THREAD

**Issue by arvit1** [kiddkai/atom-node-debugger#126]
i cant seem to figure out yet how to add,,, appArgs: "--arg1=10 --arg2" 
an example would be very appreciated 
thank you in advance

**Comment by codecontemplator** [comment]
I ussually just edit the atom config file directly as shown on the package readme page. Package settings can be edited in a ui as well in atom if you navigate to the package installer. Is that what you meant?

**Comment by codecontemplator** [comment]
You should be able to add appArgs to your config file. Something like


```
"*": 
 "node-debugger":
    nodePath: "C:/Apps/nodejs/node.exe"
    appArgs: "--arg1=10 --arg2"
    scriptMain: "C:/Users/Daniel/github/node-debugger/demo/a.js"
```
