### ISSUE TITLE
Node executable cannot be found.

### ISSUE THREAD

**Issue by gwilakers** [kiddkai/atom-node-debugger#127]
Using Mac, with El Capitan installed.

![image](https://cloud.githubusercontent.com/assets/2496236/13091194/fc48fa5a-d4c7-11e5-834c-44291538a65b.png)

My configuration file looks like this (I have removed the scriptMain for issue submission):
```
"node-debugger":
  appArgs: ""
  debugPort: 3000
  nodePath: "/usr/local/bin/node"
  scriptMain: ""
```

This is the error I recieve:
![image](https://cloud.githubusercontent.com/assets/2496236/13091241/34ad259c-d4c8-11e5-8238-65d3c372c945.png)

I am pretty confused as to why it does not see my node executable in the path that it is currently installed. The only other thing that I can think of is maybe installing node with <a href="http://brew.sh/">homebrew<a/> has something to do with it? I doubt it though. Any advice / suggestions would be great. Thanks!

**Comment by codecontemplator** [comment]
I do not own a mac. To me it seems like you are doing it right. Can you start node using the nodePath provided? Any clues in the log file (debugger.log)?

**Comment by berniszon** [comment]
Same issue here on a Mac, debugger.log contains the following line:

`{"name":"debugger","hostname":"","pid":16253,"level":50,"msg":"child_process ENOENT exit code. Message: spawn /bin/node ENOENT","time":"2016-02-19T16:38:26.067Z","v":0}`

It looks like config is not read/ignored (I have set `nodePath: "/usr/local/bin/node"` as well)

**Comment by codecontemplator** [comment]
Could it be that you are missing the top level "*" in your configuration file?

My full configuration file looks something like:

"*":
  "exception-reporting":
    userId: "44400197-0ba9-390e-5b39-d8301db8508a"
  welcome:
    showOnStartup: false
  "node-debugger":
    nodePath: "C:/Apps/nodejs/node.exe"
    scriptMain: "C:/Users/Daniel/github/node-debugger/demo/a.js"
  tabs:
    usePreviewTabs: true
  core: {}
  editor:
    invisibles: {}

**Comment by berniszon** [comment]
Yep, silly misconfiguration, works fine now.

**Comment by codecontemplator** [comment]
Sweet. Cheers.

**Comment by gwilakers** [comment]
Sorry for the late response. My issue was also with a formatting issue in the configuration. Thanks!

**Comment by tanpengsccd** [comment]
solved! 
it's OS X 10.12.2.
setting's "Node Path" is not right !
```
which node 
```
get the right path ,and paste it in you setting.

**Comment by drelbert** [comment]
Ah, this was super helpful.  I had the same error message, but modifying the config file to add the "node-debugger" line and nodePath resolved the issue.  Thank you.
