### ISSUE TITLE
Monospace font for stdout/stderr

### ISSUE THREAD

**Issue by codyhazelwood** [kiddkai/atom-node-debugger#128]
It would be nice to have a monospaced font for stdout/stderr.  Crashes that show indicators such as:

```
module.js:340
    throw err;
    ^
```

are useless in a non-monospaced font.

A good alternative would be to open a terminal window with stdout/stderr and hide that panel.

**Comment by codecontemplator** [comment]
Good point.

**Comment by codecontemplator** [comment]
fixed
