### ISSUE TITLE
not working after upgrading to 1.4.1

### ISSUE THREAD

**Issue by caglarcem** [kiddkai/atom-node-debugger#132]
Thanks for the great package.

it was ok until recently updated from 1.3.7 (afair). Now after upgrading to 1.4.1 I'm getting "Connection attempt 1 to node process on 127.0.0.1:5860 failed. Will try again in 500."

i checked the config and node path looks fine.

Any ideas?

**Comment by codecontemplator** [comment]
Hi! 

Thanks fir your feedback. Can you provide some steps for reproduction? 

Cheers

**Comment by codecontemplator** [comment]
Also, please check the log file debugger.log.

**Comment by caglarcem** [comment]
working fine after upgrading to 1.4.3. Thanks.
