### ISSUE TITLE
Save configuration in plugin config file instead of global config

### ISSUE THREAD

**Issue by alexandernst** [kiddkai/atom-node-debugger#140]
Please switch to a plugin config file instead of using the editor's config file. `config.cson` is intended for the editor's itself, not for plugins configuration.

**Comment by codecontemplator** [comment]
Ok. Thanks for the tip.

**Comment by codecontemplator** [comment]
Can you give me some reference on this? If I edit settings for some other packages they end up in the config.cson as well.

**Comment by alexandernst** [comment]
Indeed, you're right. I always thought plugins stored conf in their own files, but now I see that indeed all plugins store their settings in Atom's conf file. Sounds like a huge mess imho, but that's the way it works. Closing this as invalid.
