### ISSUE TITLE
Hitting the 'X' button doesn't clear the gutter

### ISSUE THREAD

**Issue by alexandernst** [kiddkai/atom-node-debugger#142]
The `>` symbol used to track the current line that is being debugged isn't cleared when the `X` button is pressed and the debugger is closed.

**Comment by codecontemplator** [comment]
You can use shift f5 to stop the debugger as a work around.

**Comment by alexandernst** [comment]
Will that clear the gutter?

**Comment by codecontemplator** [comment]
Problem should be fixed in 1.4.5
