### ISSUE TITLE
Question: Debugging the Debugger

### ISSUE THREAD

**Issue by origin1tech** [kiddkai/atom-node-debugger#149]
So I have a pretty complicated start up lots of flags and so on. For some reason the debugger starts it then says it can connect and will retry. It says it's then connected but doesn't load the script just pauses on being connected.

I then press the play button and it runs but almost shuts down the debugger immediately.

Now when I run this from the terminal the project starts just fine. Can debug with node-inspector and so on no worries. 

So my question is I'd like to resolve this issue and thought I'd run it by you to see if you had some ideas as to why this behavior is happening as it is. Essentially point me in the right direction if you will.

Appreciate the time...

**Comment by codecontemplator** [comment]
Please try again in the latest release. You probably get some error information in the console window.

**Comment by codecontemplator** [comment]
Please reopen if problem persists.
