### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by LideMa** [kiddkai/atom-node-debugger#15]
I have learned node & atom just a few hours.
This is node hello world code below.
```
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
```
It doesn't work to debug it in Atom.

**Comment by kiddkai** [comment]
It should work now if you adding the breakpoint to a line or add a `debugger` in your code
