### ISSUE TITLE
Getting Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by raptor235** [kiddkai/atom-node-debugger#157]
Any idea why? using default port, if I start the node app with debug on this port first it works.. but then debugger won't turn on... and vice versa.. seems that both cannot be running on the same port.

**Comment by kweiberth** [comment]
I am also getting this error.

**Comment by raptor235** [comment]
I had to kill the node process and restart… somehow node crashed and was eating
up the port.

On Tue, Mar 29, 2016 6:10 PM, Kurt Weiberth notifications@github.com wrote:
I am also getting this error.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub



--
Bart Dabek

_________________

Co-Founder & CTO of FlowPress Inc . | Sidekick.pro | WPUniversity.com

647.588.6285 | bart@flowpress.ca | @bartdabek

**Comment by kweiberth** [comment]
@raptor235 I eventually figured it out. Once your app is running with something like `node --debug .` you then want to run the Attach command from the node-debugger package, not Start.
