### ISSUE TITLE
Inspect {Date} value

### ISSUE THREAD

**Issue by nvartolomei** [kiddkai/atom-node-debugger#158]
Any way to inspect Date object value?

<img width="180" alt="screen shot 2016-03-26 at 22 30 24" src="https://cloud.githubusercontent.com/assets/543193/14062286/c9d27e50-f3aa-11e5-94ef-1a82d1a845e4.png">

**Comment by codecontemplator** [comment]
It is not possible in the watch window currently. You may write dt.toString() in the console.

**Comment by codecontemplator** [comment]
Fixed in the latest release. 
![image](https://cloud.githubusercontent.com/assets/3386085/14228631/264f6aa6-f91b-11e5-850a-4c1e587a4150.png)
