### ISSUE TITLE
Make screen estate more versatile

### ISSUE THREAD

**Issue by Redsandro** [kiddkai/atom-node-debugger#162]
Great package! :+1: 

Some suggestions.

When attaching the debugger to a node that has output redirected for reasons, the `stdout/stderror` pane is pretty much useless and taking up screen estate.

But dragging it down to make it smaller also takes away from the valuable `breakpoint/stack/locals` pane, which is already smallish and whose space is more important vertically than horizontally.

I would like to see:

* Option to hide the `stdout/stderror` pane
* Option to have the `breakpoint/stack/locals` pane on the right in stead of at the bottom.
  * (Although some people probably prefer it on the left)

**Comment by nikmartin** [comment]
I'd love to be able to break out the `breakpoint/stack/locals` window to float it like I can in other debuggers.

**Comment by codecontemplator** [comment]
Thanks for your feedback. Need to do some thinking around this. Floating windows does not sound like low-hanging fruit but I might be wrong.

**Comment by Redsandro** [comment]
@codecontemplator any update on this?

I'm inspecting big lists of variables for a project and it's really uncomfortable not being able to show the list at the side of the code/screen vertically maximized (like search results). I'm finding myself dusting off Eclipse just for the debugging.

But everyone knows, every time someone starts Eclipse an angel dies and falls from heaven.

**Comment by codecontemplator** [comment]
Thanks for your feedback. It is indeed unfortunate if angels have to die. Lets see. Maybe the time gods are good to me and gives me some time to fix this.

**Comment by Redsandro** [comment]
@codecontemplator Well here's a recepy from Jamie Oliver.

__Don't read it.__*

1. __To make your soup:__ Peel and roughly slice the carrots. Slice the celery. Peel and roughly chop the onions. Peel and slice the garlic. Put a large pan on a medium heat and add a couple of lugs of olive oil. Add all your chopped and sliced ingredients and mix together with a wooden spoon.
1. Cook for around 10 to 15 minutes with the lid askew, until the carrots have softened but are still holding their shape, and the onion is lightly golden.
1. Put the stock cubes into a jug or pan and pour in 1.5 litres of boiling water from the kettle. Stir until the stock cubes are dissolved, then add to the pan with your tinned and fresh whole tomatoes, including the green stalks that may still be attached to some of them (these give an amazing flavour – trust me!) Give it a good stir and bring to the boil. Reduce the heat and simmer for 10 minutes with the lid on. Meanwhile, pick your basil leaves.
1. __To serve your soup:__ Remove the pan from the heat. Season with salt and pepper and add the basil leaves. Using a hand blender or liquidizer, pulse the soup until smooth. Season again before dividing between your serving bowls.

*) I just saved you some time. :smile: 

It's not much, I know. It's the best I can do. I hope you can find some more time savers and accumulate the time to look into this.

**Comment by codecontemplator** [comment]
I started experimenting a bit with separate columns for each panel.

![image](https://cloud.githubusercontent.com/assets/3386085/18226872/5367db2e-7213-11e6-8cfb-723c4245865e.png)

Any opinions?

**Comment by codecontemplator** [comment]
Collapsed panels:

![image](https://cloud.githubusercontent.com/assets/3386085/18227188/60f5052e-721c-11e6-9991-51e0b2924404.png)

**Comment by Redsandro** [comment]
Looks good but the most important thing is the option to put it to the
right of the code and use the full vertical space of the screen. To be able
to collapse these others is extra valuable when stacked vertically. The
holy grail would be detaching them on separate windows.

Btw I love the watches!

**Comment by codecontemplator** [comment]
@Redsandro is something like this what you are looking for?

![image](https://cloud.githubusercontent.com/assets/3386085/19168788/16281bc0-8c12-11e6-95a1-454cabc0a539.png)

**Comment by Redsandro** [comment]
@codecontemplator Yes!!

Can the stdout (optionally) go there too? I prefer to tuck it away, hide it or close it. Many of the apps I'm working on don't produce stdout.

**Comment by codecontemplator** [comment]
The console can be minimized using the splitter. Changes merged into master. Thanks for good input.

**Comment by Redsandro** [comment]
I had a chance to try this out. This is a lot better! :+1: I can just semi-hide the `stdio` panel by dragging the border.

Nice job.

**Comment by codecontemplator** [comment]
Thanks @Redsandro . I just added in expand/collapse functionality as well so feel free to update again :)

**Comment by Redsandro** [comment]
@codecontemplator could you please add the option in settings to collapse the `stdout/stderr` by default? :boom: :sparkles: :tada: :kissing_heart:
