### ISSUE TITLE
Array versus Object formatting

### ISSUE THREAD

**Issue by Redsandro** [kiddkai/atom-node-debugger#166]
Currently, arrays and objects are listed like so:

```
> objTest: Object { ... }
> testArr: Array { ... }
``` 

Visual clues are very important. It should be like this:

```
> objTest: Object { ... }
> testArr: Array [ ... ]
``` 

Better yet, when expanding the `Array`, there is a `length` attribute. This should also be visible in the collapsed Array like so:

```
> objTest: Object { ... }
> testArr: Array [ 16 ]
```

**Comment by codecontemplator** [comment]
Good idea.

**Comment by codecontemplator** [comment]
Fixed
