### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by AkashSouravNayak** [kiddkai/atom-node-debugger#175]
whenever i am trying to debug i am getting this error.Help me to fix this.
 Exit code was ENOENT which indicates that the node executable could not be found. Try specifying an explicit path in your atom config file using the node-debugger.nodePath configuration setting.

**Comment by ghns** [comment]
I am think what you have specify path to node.exe in nodePath.

**Comment by jsguy** [comment]
Had same problem, fixed it (on Mac) by:

1. Open Settings
2. Click the "Open config folder" button
3. Open "config.cson"
4. Add the following near the bottom:

```
  "node-debugger":
    nodePath: "/usr/local/bin/node"
```

Restart Atom, and it works.
