### ISSUE TITLE
Ramda

### ISSUE THREAD

**Issue by madmax911** [kiddkai/atom-node-debugger#176]
Says it's missing dependency ramda.  (Ramda's installed btw)

On windows build 1.8.0

When you get it fixed could you please let me know.  maxone44@hotmail.com

Thanks.

**Comment by codecontemplator** [comment]
Hi, 
How did you install the node debugger package? When installed using the atom package manager (either from the command line or from within atom using the ui) this should not be a problem. 
Cheers
