### ISSUE TITLE
The frame stdout / stderr crushes debug panel controls when displaying large logs.

### ISSUE THREAD

**Issue by Jeffersonmf** [kiddkai/atom-node-debugger#180]
The frame stdout / stderr crushes debug panel controls when displaying large logs.

Is there a way to make FIXED ?
or clean the console.log in stdout / stderr window? (to force the controls panel appear again)

thank you.

**Comment by codecontemplator** [comment]
Work on #162 should try to fix this.

**Comment by codecontemplator** [comment]
@Jeffersonmf would you mind attaching a screen shot?

**Comment by Jeffersonmf** [comment]
Hi,

When I did start the debug process.

It all starts well, however depending on the amount of logs that was show
on the stderr / stdout panel, everything is "crushed" on the right side.

As you can see in the last picture.

When this happens, not can pull again the panel splitter,because is the
same border of the Atom window that's captured by mouse. The divisor of
panel disappears.

This situation can me force stop and restart the process at the beginning.

Thank you so much for support.


2016-09-03 16:39 GMT-03:00 Daniel Brännström <notifications@github.com>:

**Comment by codecontemplator** [comment]
Thanks for getting back. I do not see the picture you are referring to? Would you mind trying again?

**Comment by codecontemplator** [comment]
Think this is solved in the latest release. Please reopen if not

**Comment by Jeffersonmf** [comment]
Awesome !

Thank you so much !!

Great Job !

2016-10-12 19:17 GMT-03:00 Daniel Brännström <notifications@github.com>:
