### ISSUE TITLE
Typo in README.md Commands section

### ISSUE THREAD

**Issue by GaborFarkas** [kiddkai/atom-node-debugger#182]
There is a minor typo in the Commands section describing the command for debugging the active file as `'node-debugger:debug-active-file' (ctrl-F5)`, while it is `'node-debugger:start-active-file'` as stated in [node-debugger.cson](https://github.com/kiddkai/atom-node-debugger/blob/master/keymaps/node-debugger.cson#L12).

This typo can affect some Linux users, as in some distros CTRL+F5 is already mapped to switching to the fifth workspace, and they might want to change that key binding.

**Comment by codecontemplator** [comment]
thanks for reporting
