### ISSUE TITLE
Object references or IDs in tree

### ISSUE THREAD

**Issue by Redsandro** [kiddkai/atom-node-debugger#183]
Can we get a reference identification in the tree view for objects/arrays?

```
req: Object
    connection: Object { ... } #15
    res: Object { ... } #16
    trailers: Object { ... } #17
res: Object { ... } #16
```

Eclipse does something similar:

![image](https://cloud.githubusercontent.com/assets/1702193/17214187/06bf724e-54d8-11e6-99b7-a5ad37b94d4c.png)

It's convenient for eyeballing references.

**Comment by codecontemplator** [comment]
Sounds like low hanging fruit. Why not? I think it is a good idea.

**Comment by Redsandro** [comment]
https://youtu.be/-QRZpligDOs

**Comment by codecontemplator** [comment]
Implemented and merged to master. Sample screen shot:

![image](https://cloud.githubusercontent.com/assets/3386085/19216052/0f00c6c8-8daf-11e6-9fbb-d7b69b25dad5.png)
