### ISSUE TITLE
BUG  : If log's  lenght is too long ,the console‘s button would disappear

### ISSUE THREAD

**Issue by Moerslion** [kiddkai/atom-node-debugger#185]

**Comment by codecontemplator** [comment]
@Moerslion can you provide a screen shot?

**Comment by Moerslion** [comment]
![3](https://cloud.githubusercontent.com/assets/16080054/18303115/0a5c6672-750e-11e6-8ae8-b076b9e4e034.png)

**Comment by codecontemplator** [comment]
Seems to be working better after the layout update in version 1.8.
