### ISSUE TITLE
Support NPM run scripts

### ISSUE THREAD

**Issue by trainerbill** [kiddkai/atom-node-debugger#192]
Instead of configuring the nodePath, can you support running an npm run script?  like npmDebugScript: "npm run debug" or something similar?  I have to run babel-node local on the project and can't find a good way to get this done without installing babel globally.  Being able to execute npm scripts would give much more flexibility.

**Comment by codecontemplator** [comment]
@trainerbill I do not understand how npm scripts should be used to replace the need for the debugger to find the node.js executable? can you please elaborate?

**Comment by trainerbill** [comment]
I switched to VS code and really don't remember why this didn't work.
