### ISSUE TITLE
Newbie Lost On Instructions

### ISSUE THREAD

**Issue by Mookh01** [kiddkai/atom-node-debugger#193]
First, thank you very much for the work done with atom-node-debugger.  Please know I'm appreciative and grateful for what you've done.  

I keep getting this message _**### (Failed to start debugger. Exit code was ENOENT which indicates that the node executable could not be found. Try specifying an explicit path in your atom config file using the node-debugger.nodePath configuration setting)**_

Being new to coding its difficult to understand your directions.   
What do you mean when you say;

- Open a javascript (.js) file and execute the start-resume command (F5) to launch the debugger. ??     **Is this an existing javascript file or a a new file? Am I needing to put something in it?**

- The '>' symbol in the gutter marks the current line of execution.   **I am not getting the symbol in the debugger windows.**

- **I don't understand the Configuration, you mention "set to control" but you do not reference where to find the controls, where are they....specifically**. 

- **As for the example configuration, is the supposed to be in a .json file? Where does it go?**

Thank you regardless.

**Comment by codecontemplator** [comment]
@Mookh01 thanks for trying out the atom node debugger. the error message indicates that your node.js executable cannot be found. From the file menu in atom you can open your config file and specify the path explicitly.
