### ISSUE TITLE
finish debugging :)

### ISSUE THREAD

**Issue by cipiripper** [kiddkai/atom-node-debugger#203]
I really like your package guys, but this info message (notification) in Atom after you finish debugging:

```
finish debugging :)
finish debugging :)
finish debugging :)
```

_Is really spammy - BECAUSE YOU CANNOT CANCEL INFO NOTIFICATIONS IN ATOM!_ So this message stays there, and if I need to click on something under it - I can't until it hides...

Please just hide it?

**Comment by codecontemplator** [comment]
Thanks! :)
I think indeed that the messages does not add much value anymore.

**Comment by codecontemplator** [comment]
Just removed the messages to see if anyone will miss them :)
