### ISSUE TITLE
Debug buttons covered by notifications

### ISSUE THREAD

**Issue by aneilbaboo** [kiddkai/atom-node-debugger#218]
After starting the debugger, the debug buttons are covered by notifications.

Am I the only who is seeing this?  

![debug-buttons-covered](https://cloud.githubusercontent.com/assets/2592723/21691742/b10c790c-d32e-11e6-8f96-ab0d5c92b572.gif)

It would be nice to have an option to disable notifications.  The debug console provides the same feedback.

**Comment by codecontemplator** [comment]
@aneilbaboo No you are not the only one :)

See #203
