### ISSUE TITLE
Not clear how to trigger this on a Macbook Pro with touchbar

### ISSUE THREAD

**Issue by jim-moody** [kiddkai/atom-node-debugger#232]
In the documentation, it says to trigger this debugger using f5, but there is no f5 key on a macbook pro with touchbar.

**Comment by chmac** [comment]
You can use <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> to open the Command Palette which then lets you type to choose commands including all the node debugger commands.

**Comment by mihkel55** [comment]
press the fn key and all the f keys appear in touchbar

**Comment by jim-moody** [comment]
Now I feel like an idiot..thanks haha
