### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by samijnih** [kiddkai/atom-node-debugger#36]
In stylesheets\gutter-breakpoint.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by kiddkai** [comment]
Thanks @samijnih, this issue have been fixed in https://github.com/kiddkai/atom-node-debugger/pull/39/files
