### ISSUE TITLE
Breakpoint Add: Cannot add

### ISSUE THREAD

**Issue by Arsca** [kiddkai/atom-node-debugger#38]
Hi,

I'm trying to figure out how to use this package. I'm coming from WebStorm. 

I start my app as indicated 
```$ node app.js ```
and then I understand that I should add a breakpoint, but as I do it there are no visual indications of it in the editor and in the debugger window I cannot see any breakpoints set either.

What are the correct steps to debug from atom: 
   - Should atom-node-debugger be started before adding any  breakpoints?

**Comment by kiddkai** [comment]
It doesn't have that feature yet. But it's doable. For the usage. `node app.js` may not working in this case.

You can go to the setting view of the atom-node-debugger and choose your runnable binary of node. Then is should be able to run your file using `cmd+shift+p` and type in `debug current file`. Then it should work.

Currently this debugger only works in the file level not project level :cry:

**Comment by jhopper28** [comment]
What's the trick to getting this to work? I can't add a breakpoint or get debugging started. And I don't have a `debug current file` option in the command palette.

**Comment by kiddkai** [comment]
Hi @jhopper28 ,

According to the latest README, use `f5` to debug the current file. Can you try it out?

Cheers

**Comment by jhopper28** [comment]
That conflicted with another key mapping so I just tried it from the atom command palette which doesn't do anything.

**Comment by tonyfung99** [comment]
I couldn't add any breakpoint too. I can open the debugger console but cannot do anything with it. 

My config
Mac OS 10.10.4
Atom 1.0
node v0.12.1

**Comment by kiddkai** [comment]
Is there any error shows up?

**Comment by tonyfung99** [comment]
Thanks for your timely response.

No any error indicated. Doesn't have any response after pressing F9

![screen shot 2015-07-10 at 5 20 59 pm](https://cloud.githubusercontent.com/assets/2355642/8615743/3f8e1118-2728-11e5-9180-c8098a0b5aab.png)

**Comment by codecontemplator** [comment]
Hi @tonyfung99,

It looks like the debugger failed to connect. If the startup was successful you should have a message 'Debugger listening on port XXXX' in the stdout/stderr pane. 

Are there any clues in the log file debugger.log?

**Comment by Sean-Wang** [comment]
@tonyfung99 You should change Node path in atom-node-debugger setting. For Mac OS X, `Node Path` is `/usr/local/bin/node`.

**Comment by tonyfung99** [comment]
Thanks guys. After updated to the latest version, it's work now. Cheers.

**Comment by kiddkai** [comment]
Thanks @tonyfung99
