### ISSUE TITLE
Config written under "node-debugger" key instead of "atom-node-debugger" key

### ISSUE THREAD

**Issue by danielvanmil** [kiddkai/atom-node-debugger#40]
Hello,

Installed package, but did not work out of the box.
Checking some exceptions showed me the config was incorrect and is written to the "node-debugger" instead of the "atom-node-debugger" that is read from.

Or maybe this is an environmental issue? (atom version, windows, ...)

**Comment by slhad** [comment]
Hi,

I encounter the same problem on linux.

**Comment by avielfedida** [comment]
Having the same problem on Atom 1.0(windows 8.1).

**Comment by kiddkai** [comment]
This issue fixed https://github.com/kiddkai/atom-node-debugger/commit/7a936d42347f2bb04112afe83c9be951adb46b03
