### ISSUE TITLE
Debugger not working with error "Unhandled promise rejection %o with error %o"

### ISSUE THREAD

**Issue by notsyncing** [kiddkai/atom-node-debugger#41]
Hello,

I installed this plugin version 1.1.0 and found it not working. When I press F5 on a javascript file, it popups the debugger pane but nothing happening then. Everything typed in the command line results a "Cannot read property 'req' of null" error.

Running "atom -f" gives following output:
[21323:0624/212107:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[21323:0624/212107:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
App load time: 315ms
[21323:0624/212108:INFO:CONSOLE(612)] "'node-debugger.nodeArgs' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /usr/share/atom/resources/app.asar/src/config.js (612)
[21323:0624/212108:INFO:CONSOLE(612)] "'node-debugger.appArgs' could not set the default. Attempted default: undefined; Schema: {"type":"string"}", source: /usr/share/atom/resources/app.asar/src/config.js (612)
[21323:0624/212109:INFO:CONSOLE(56)] "Window load time: 1556ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (56)
<After press F5>
[21323:0624/212119:INFO:CONSOLE(14)] "Unhandled promise rejection %o with error: %o", source: file:///usr/share/atom/resources/app.asar/static/index.js (14)

I'm running atom 0.211.0 on Ubuntu 15.10 amd64 with atom-node-debugger 1.1.0 .

**Comment by rahatm1** [comment]
Same here.

**Comment by kiddkai** [comment]
Hey @rahatm1 @notsyncing , It seems that it's the same issue as this one : https://github.com/kiddkai/atom-node-debugger/issues/40,

Will make a patch to this bug very soon.

**Comment by kiddkai** [comment]
Hi, can you give me a way to reproduce this issue, I can't reproduce it in my machine. soz

**Comment by notsyncing** [comment]
Now with 1.1.4(or any version after 1.1.1) in atom 1.0 it can start debugging but seems unstable.
I wrote a js with one line: "console.info("hello, world");" and press F5 to start debug, it printed the correct "Hello, world" and finished. But after the second run finished, it refused to start debug again, even press Shift+F5 then F5 again cannot make it work anymore.

Console output:
[17332:0707/194718:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[17332:0707/194718:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
App load time: 378ms
[17332:0707/194720:INFO:CONSOLE(20)] "activate linter-jshint", source: /home/sfc/.atom/packages/linter-jshint/lib/init.coffee (20)
[17332:0707/194720:INFO:CONSOLE(56)] "Window load time: 1473ms", source: file:///opt/atom/resources/app.asar/static/index.js (56)
[17332:0707/194734:INFO:CONSOLE(20)] "activate linter-jshint", source: /home/sfc/.atom/packages/linter-jshint/lib/init.coffee (20)
[17332:0707/194734:INFO:CONSOLE(56)] "Window load time: 1679ms", source: file:///opt/atom/resources/app.asar/static/index.js (56)
[17332:0707/194742:INFO:CONSOLE(93)] "debugger listening on port 5858
", source: /home/sfc/.atom/packages/node-debugger/lib/Components/ConsolePane.coffee (93)
[17332:0707/194747:INFO:CONSOLE(90)] "Hello, world!
", source: /home/sfc/.atom/packages/node-debugger/lib/Components/ConsolePane.coffee (90)
[17332:0707/194749:INFO:CONSOLE(93)] "debugger listening on port 5858
", source: /home/sfc/.atom/packages/node-debugger/lib/Components/ConsolePane.coffee (93)
[17332:0707/194750:INFO:CONSOLE(90)] "Hello, world!
", source: /home/sfc/.atom/packages/node-debugger/lib/Components/ConsolePane.coffee (90)
[17332:0707/194759:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[17332:0707/194800:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)
[17332:0707/194800:INFO:CONSOLE(232)] "(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.", source: events.js (232)

**Comment by kiddkai** [comment]
Can you check your configuration is correct? If node path is not configured properly then it won't runs. You can view all the detail logs in the package directory. Which called `debugger.log`. Which is a bunyan log. You can read it using bunyan though.

Anyway, the error handling about this plugin still needs improvement.

**Comment by notsyncing** [comment]
All configurations are correct, in fact it can run several times before error.
The debugger.log only gives me these when it doesn't work:
{"name":"debugger","hostname":"sfc-K580P","pid":17704,"level":30,"msg":"app init { height: { [Function: observable] set: [Function] },\n  sideWidth: { [Function: observable] set: [Function] },\n  channels: { changeHeight: [Function], changeWidth: [Function] },\n  steps: \n   { stepIn: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     stepOut: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     stepNext: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     stepContinue: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' } },\n  breakpoints: \n   { [Function: observable]\n     set: [Function: trackDiff],\n     rootToggle: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        isOn: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     breakpoints: { [Function: observable] set: [Function] },\n     _type: 'observ-struct',\n     _version: '5' },\n  callstack: \n   { [Function: observable]\n     set: [Function: trackDiff],\n     rootToggle: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        isOn: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     frames: \n      { [Function: observable]\n        set: [Function: set],\n        splice: [Function: splice],\n        _observSet: [Function],\n        get: [Function: get],\n        getLength: [Function: getLength],\n        put: [Function: put],\n        transaction: [Function: transaction],\n        _list: [],\n        _removeListeners: [],\n        _type: 'observ-array',\n        _version: '3',\n        push: [Function: observArrayPush],\n        pop: [Function: observArrayPop],\n        shift: [Function: observArrayShift],\n        unshift: [Function: observArrayUnshift],\n        reverse: [Function: reverse],\n        sort: [Function: sort],\n        concat: [Function],\n        slice: [Function],\n        every: [Function],\n        filter: [Function],\n        forEach: [Function],\n        indexOf: [Function],\n        join: [Function],\n        lastIndexOf: [Function],\n        map: [Function],\n        reduce: [Function],\n        reduceRight: [Function],\n        some: [Function],\n        toString: [Function],\n        toLocaleString: [Function] },\n     _type: 'observ-struct',\n     _version: '5' },\n  logger: \n   { [Function: observable]\n     set: [Function: trackDiff],\n     lines: \n      { [Function: observable]\n        set: [Function: set],\n        splice: [Function: splice],\n        _observSet: [Function],\n        get: [Function: get],\n        getLength: [Function: getLength],\n        put: [Function: put],\n        transaction: [Function: transaction],\n        _list: [],\n        _removeListeners: [],\n        _type: 'observ-array',\n        _version: '3',\n        push: [Function: observArrayPush],\n        pop: [Function: observArrayPop],\n        shift: [Function: observArrayShift],\n        unshift: [Function: observArrayUnshift],\n        reverse: [Function: reverse],\n        sort: [Function: sort],\n        concat: [Function],\n        slice: [Function],\n        every: [Function],\n        filter: [Function],\n        forEach: [Function],\n        indexOf: [Function],\n        join: [Function],\n        lastIndexOf: [Function],\n        map: [Function],\n        reduce: [Function],\n        reduceRight: [Function],\n        some: [Function],\n        toString: [Function],\n        toLocaleString: [Function] },\n     _type: 'observ-struct',\n     _version: '5' },\n  cancel: \n   { [Function: observable]\n     set: [Function: trackDiff],\n     channels: { [Function: observable] set: [Function] },\n     _type: 'observ-struct',\n     _version: '5' } }","time":"2015-07-07T13:47:45.349Z","v":0}
{"name":"debugger","hostname":"sfc-K580P","pid":17704,"level":30,"msg":"app state { height: 350,\n  sideWidth: 400,\n  channels: \n   { changeHeight: { type: 'dom-delegator-handle' },\n     changeWidth: { type: 'dom-delegator-handle' } },\n  steps: \n   { stepIn: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     stepOut: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     stepNext: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' },\n     stepContinue: \n      { [Function: observable]\n        set: [Function: trackDiff],\n        title: [Object],\n        type: [Object],\n        waiting: [Object],\n        channels: [Object],\n        _type: 'observ-struct',\n        _version: '5' } },\n  breakpoints: \n   { rootToggle: { title: 'Breakpoints', isOn: false, channels: [Object] },\n     breakpoints: [] },\n  callstack: \n   { rootToggle: { title: 'Call Stack', isOn: false, channels: [Object] },\n     frames: [] },\n  logger: { lines: [] },\n  cancel: { channels: { cancel: [Object] } } }","time":"2015-07-07T13:47:45.351Z","v":0}
{"name":"debugger","hostname":"sfc-K580P","pid":17704,"level":30,"msg":"child_process_children []","time":"2015-07-07T13:47:45.375Z","v":0}

**Comment by rahatm1** [comment]
Works fine for me as of last release. Thanks!

**Comment by kiddkai** [comment]
No worries mate
