### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by radjivC** [kiddkai/atom-node-debugger#48]
Hi,
Your work looks fantastic, but can you make a tutorial? 
Like I downloaded, copy it in my file the config node-debugger/keymaps/node-debugger.cson 

(I'm working on macosx)
````
'atom-workspace':
  'f5': 'node-debugger:start-resume'
  'shift-f5': 'node-debugger:stop'
  'f9': 'node-debugger:toggle-breakpoint'
  'f10': 'node-debugger:step-next'
  'f11': 'node-debugger:step-in'
  'shift-f11': 'node-debugger:step-out'

"atom-node-debugger":
  nodePath: "/usr/local/bin/node"
  appArgs: ""
  debugPort: 5860
`````

If I press F5 the panels appear

But I can't make a breakpoint on my js files,

do I need to make more configuration or something?

Thx

**Comment by kiddkai** [comment]
oh, you just need to use `'f9': 'node-debugger:toggle-breakpoint'` to add the breakpoint

**Comment by radjivC** [comment]
I have tried many time but nothing happens :disappointed:

**Comment by kiddkai** [comment]
does it shows debug finished directly?

**Comment by radjivC** [comment]
when I do 
````
' f9': 'node-debugger:toggle-breakpoint' 
`````
it doesn't  mark the gutter red after the breakpoint added
and it shows the debug finished directly

**Comment by kiddkai** [comment]
oh, if you hit this issue which mean that child process start failure, can
you please check if your node path configure correctly?

**Comment by radjivC** [comment]
Yes my path is correct but I put it in this file "node-debugger/keymaps/node-debugger.cson" is that wrong?

**Comment by kiddkai** [comment]
Interesting.....I think you should use the setting ui to do the configuration to a plugin

**Comment by radjivC** [comment]
perfect it works now thanks

**Comment by kiddkai** [comment]
Yay ◕ฺ‿◕ฺ✿ฺ)-
