### ISSUE TITLE
Execute Node In Script Dir

### ISSUE THREAD

**Issue by SC7639** [kiddkai/atom-node-debugger#49]
I can't figure out how to get node to execute in the Script's directory not atom's directory. When I execute my code the relative file paths  don't resolve to the correct file. E.g. My jade views in my express app.

**Comment by kiddkai** [comment]
Interesting issue, I'll take a look to see if it have the same issue here.

**Comment by SC7639** [comment]
Thanks

**Comment by kiddkai** [comment]
fixed, closing this issue

**Comment by SC7639** [comment]
Fantastic thankyou.
