### ISSUE TITLE
Debugger shutdown fails on a clean windows installation

### ISSUE THREAD

**Issue by codecontemplator** [kiddkai/atom-node-debugger#50]
# Steps to reproduce
1. Open a .js file such as a.js in the demo folder
2. Press F5 to start debugger
3. Press shift-F5 to stop debugger

# Result
'ps' could not be spawned.
'kill' coudl not be spawned.

![image](https://cloud.githubusercontent.com/assets/3386085/8607356/953ccac8-2692-11e5-9681-cd046e273fd1.png)

# Analysis
The reason for the error messages is that neither kill.exe or ps.exe exist on a clean windows installation.

# Possible fix
Use tree-kill instead.
https://www.npmjs.com/package/tree-kill

# Known workarounds
If you have GIT command line client (https://git-scm.com/download/win) installed you can add the bin folder to your path. This works since the bin folder contains both kill.exe and ps.exe.

**Comment by kiddkai** [comment]
nice one，thanks for helping me get this error
