### ISSUE TITLE
Console output is not scrollable or cleanable

### ISSUE THREAD

**Issue by renannprado** [kiddkai/atom-node-debugger#53]
It is not possible to clean or to scroll the console output inside of Atom.

**Comment by kiddkai** [comment]
Do you mean close the debugger? if it is, try shift+f5

**Comment by codecontemplator** [comment]
If (or when) console log overflows no scrollbar appears (and it is not possible to clear either).

![image](https://cloud.githubusercontent.com/assets/3386085/8628602/b9452060-2754-11e5-89e7-02ed3d86903c.png)

**Comment by renannprado** [comment]
I was about to send screen shot. Thanks :)
