### ISSUE TITLE
Error on Atom 1.0.2

### ISSUE THREAD

**Issue by montogeek** [kiddkai/atom-node-debugger#54]
![screen shot 2015-07-09 at 21 15 37](https://cloud.githubusercontent.com/assets/1002461/8610996/ba4fb3c4-267f-11e5-8da2-73b6a5b76104.png)

It happens when I try to set a breackpoint

**Comment by kiddkai** [comment]
I'll investigate on it, thanks for the reporting

**Comment by breandr** [comment]
+1

**Comment by agileago** [comment]
+1

**Comment by kiddkai** [comment]
Hey @agileago, is there steps to reproduce this issue?

**Comment by agileago** [comment]
mac 10.10 atom 1.0.2
i just install the package . but i can't set a breakpoint just like top

**Comment by kiddkai** [comment]
@agileago did you start the debugger already?

It need you:

1. debug current file(f5)
2. add the debugger

This debugger currently doesn't have the pre-add breakpoint function before debugger started, soz

**Comment by agileago** [comment]
<img width="1102" alt="qq20150726-1 2x" src="https://cloud.githubusercontent.com/assets/11799110/8892277/a98eb3cc-3382-11e5-8394-8d9b5359ca56.png">

**Comment by agileago** [comment]
i enter `F5` button . and then enter `F9`   . it can't set

**Comment by agileago** [comment]
by the way. Do you speak Chinese ?

**Comment by kiddkai** [comment]
yeah, I can~

**Comment by kiddkai** [comment]
貌似你那边 stdout/stderr 里面也是什么都没有 :(

**Comment by agileago** [comment]
😄，我以为你是外国人呢，就是这个debugg在atom上不起作用

**Comment by kiddkai** [comment]
感觉像是子进程没启起来

**Comment by agileago** [comment]
是不是其他插件影响了

**Comment by kiddkai** [comment]
中国人中国人，翻墙出来工作而已 :smile:

**Comment by agileago** [comment]
你那边OK？

**Comment by kiddkai** [comment]
应该不是，你在 setting 里面把 Node Path 设置一下？

**Comment by kiddkai** [comment]
`cmd + shift + p` -> `Packages` -> 搜 `node-debugger` -> `settings` -> NodePath

**Comment by agileago** [comment]
<img width="592" alt="qq20150726-2 2x" src="https://cloud.githubusercontent.com/assets/11799110/8892301/d1482050-3383-11e5-8ef8-5259922532bc.png"> 

是这个，对吧！

**Comment by kiddkai** [comment]
```bash
$ which node
/path/to/io.js/v2.1.0/bin/node
```

**Comment by agileago** [comment]
`/usr/local/bin/node`

**Comment by kiddkai** [comment]
嗯，你试试把 NodePath 设置成这个行不行，我不记得我有没有加 `symlink` 支持了。

**Comment by agileago** [comment]
ok了，好了能调试了，谢谢啊

**Comment by kiddkai** [comment]
:dancers:

**Comment by kiddkai** [comment]
Hey @montogeek @breandr, seems like this issue related to the settings in the `NodePath`. The reason why shows that error is that the child process can not be created. So the solutions will be:

1. cmd + shift + p -> Packages -> search `node-debugger` -> settings -> NodePath
2. set it with value `which node` (your node.js binary path) in `bash`

If it still not working, maybe the case like `/bin/node` symlink to `/bin/iojs`. Then you need to use the `/bin/iojs` one.

Or simpler:

```bash
readlink `which node` | pbcopy
```

**Comment by kiddkai** [comment]
@agileago 欢迎 pr :dancers: :dancers: :dancers: :dancers:
