### ISSUE TITLE
Nothing happened when i clicked `run` after i clicked `auto fill`

### ISSUE THREAD

**Issue by SmallAiTT** [kiddkai/atom-node-debugger#6]
I typed `ctrl+alt+n` to open the Node Debugger, then clicked `auto fill`, and i clicked `run`, but noting happened.

And the args in the inputs disappeared.
How can i debug nodejs in atom editor with `Node Debugger`?

**Comment by kaanyilgin** [comment]
I have same problem. Auto fill doesn't work and I can't type anything in node path or application path. 

Atom Version: 0.187.0
Node Version: 0.12

**Comment by brandwe** [comment]
Same for me

OS: 10.10.3
Atom Version: 0.192.0
Node Version: v0.12.0
Node Version:Node Executable: ~/.nvm/current/bin/node

**Comment by jhopper28** [comment]
Same here…any way to enter those values manually?
