### ISSUE TITLE
Not working for me at all

### ISSUE THREAD

**Issue by pitosalas** [kiddkai/atom-node-debugger#60]
I probably have a configuration problem but I can't tell what it is.

I am on mac, node 0.12.4, atom 1.0.2.

When I click F12, all I get is a window that says "finish debugging :)"

Any help would be greatly appreciated!

![screen shot 2015-07-13 at 11 34 06 am](https://cloud.githubusercontent.com/assets/44681/8653595/330f5f0a-2953-11e5-911c-86ddf3e800bb.png)

**Comment by kiddkai** [comment]
Hey, please check if your node binary path is correctly configured

**Comment by pitosalas** [comment]
Yeah that was it. I thought since I installed it to its default location I thought it would not require any special set up.
