### ISSUE TITLE
fs.readFileSync() & fs.readdirSync() returns error 

### ISSUE THREAD

**Issue by dardourimohamed** [kiddkai/atom-node-debugger#62]
Instruction :
var fs = require('fs');
try {
  var content = fs.readFileSync('./file.ext', 'utf8');
} catch (e) {
  console.log(e);
}

Console :
{[Error: ENOENT: no such file or directory; open './file.ext']
errno:-2,
code: 'ENOENT',
syscall: 'open',
path: './file.ext'}

**Comment by kiddkai** [comment]
same issue as #49

**Comment by kiddkai** [comment]
https://github.com/kiddkai/atom-node-debugger/issues/49

**Comment by kiddkai** [comment]
Hey @dardourimohamed , it's fixed in the latest version, 1.1.6, update and the issue will no longer exists

**Comment by dardourimohamed** [comment]
Thanks, it's working
