### ISSUE TITLE
Cant close debugger pane

### ISSUE THREAD

**Issue by ujc** [kiddkai/atom-node-debugger#65]
Hi,

I couldn't find how to close the debugger pane ?
(I'm using the 'atom-material-ui' theme with 'atom-material-syntax' - in case that makes any difference).

Currently, I need to restart atom to close the debugger pane.

Any ideas ?

**Comment by codecontemplator** [comment]
Have you tried shift-F5?

**Comment by ujc** [comment]
How did I miss that ?? 
Apologies - and thanks for a great plugin!
