### ISSUE TITLE
Is it possible to have the plugin not jump to line 1 when starting the debugger?

### ISSUE THREAD

**Issue by dsifford** [kiddkai/atom-node-debugger#69]
This isn't that big of a deal, but it's kind of annoying when I'm working on lines toward the end of my file. 

Thanks! Great work!

**Comment by basarat** [comment]
> but it's kind of annoying when I'm working on lines toward the end of my file.

It basically takes you the point where its paused. Without this it would be difficult to see *current point of execution*.

**Comment by dsifford** [comment]
I guess a better question then would be: how do I remove the default break point (which is currently set at line 1)?

This is the second day I've had the plugin installed so there is a tremendously high possibility that I just overlooked something. Thanks for the help, sir!

**Comment by basarat** [comment]
> This is the second day I've had the plugin installed so there is a tremendously high possibility that I just overlooked something

One possibility is to duplicate the tab (checkout https://atom.io/packages/pain-split for an easy way to do this) and *then* start debugging in the new tab ... thus you don't lose your editing position in the current tab. 

Just a suggestion :rose:

**Comment by dsifford** [comment]
Ooooh, didn't even think of that! I like your style!

I'll give that a shot. Thanks for the tip!
