### ISSUE TITLE
Typo in event name

### ISSUE THREAD

**Issue by rumkin** [kiddkai/atom-node-debugger#71]
Event called `procssCreated` instead of `processCreated`.

https://github.com/kiddkai/atom-node-debugger/blob/master/lib/Components/ConsolePane.coffee#L79
https://github.com/kiddkai/atom-node-debugger/blob/master/lib/debugger.coffee#L55
https://github.com/kiddkai/atom-node-debugger/blob/master/lib/debugger.coffee#L116

**Comment by codecontemplator** [comment]
Fixed
