### ISSUE TITLE
Support Environment Variables

### ISSUE THREAD

**Issue by ben-page** [kiddkai/atom-node-debugger#75]
It would be nice to be able to set environment variables for the spawned process.

**Comment by xsellier** [comment]
+1

**Comment by limafelipe** [comment]
+1

**Comment by notABluesSinger** [comment]
+1

**Comment by xsellier** [comment]
[Here a Pull Request](https://github.com/kiddkai/atom-node-debugger/pull/79) for this feature

**Comment by codecontemplator** [comment]
FIxed. @xsellier the pr i still open and we can discuss improvements there.
