### ISSUE TITLE
Linux/ubuntu: Unable to set breakpoint

### ISSUE THREAD

**Issue by niedomnie** [kiddkai/atom-node-debugger#76]
I am working on Linux Debian 7.0, default theme (but I've checked on different as well)
Version of Atom 0.194.0 (and 1.0.9), node-debugger 1.1.8

F9 - does not work,
I have redefined shortcut and same situation 
No red mark on editor, no breakpoint line in a breakpoint list.
Only starting and stopping works.

**Comment by kiddkai** [comment]
Hey, does the node process start correctly? Maybe that's why the breakpoint is not able to be added.

**Comment by niedomnie** [comment]
Hello, thx for reply.

I know a little more.
Node starts correctly (in my case node application is on run remotely on different machine which should not matter). And Atom runs command node --debug-brk=<port> script.js.
When I created script (pass it to atom config) which runs only node (I've removed other parameters), and another instance is run on other host (with --debug=<port>) then atom is connecting to that node and does debugging (of course I have to fight of binding to localhost - but this is node discomfort).
Unfortunately debugging by atom is very uncomfortable: resume works sometimes (even one on every two, does not work F5 (only arrow works for me), breakpoints cannot be cleared (and exists from other sessions not stopping application though),  windows of debugger does not keep sizes (every time need to resize them again, there is no watch, variables are on stack instead of in another window like in other debuggers, fold of stack is collapsing every caught breakpoint, it is very slow (noticeable slower then Eclipse Enide, visual studio & webStrom), and paths are absolute so on remote machine and local machine has to have same path (even links does not help). 

I know that this is not a commercial tool but what is implemented would be enough for me if it will work as designed.

Sorry for complaining it it not appropriate place - but I cannot resist.
I hope that problems eventually will be solved (personally I am not able to help) because small and fast editor like atom is for me much better then obese e.g. Eclipse.

Regards.

**Comment by kiddkai** [comment]
Hey @niedomnie , thanks for your feedback. There's a lot of things need to do about this debugger to make it actually works well.

**Comment by someone235** [comment]
Same problem for me in Ubuntu 15.04

**Comment by codecontemplator** [comment]
@someone235 Can you retest this in the lastest release? I was able to run this package in atom under ubuntu without experiencing this problem.

**Comment by someone235** [comment]
I've upgraded to the latest version of Atom and node-debugger, and now it works.

**Comment by codecontemplator** [comment]
Perfect. Thanks for testing. :+1:
