### ISSUE TITLE
Breakpoints Disappear When Node Process Stops  

### ISSUE THREAD

**Issue by SC7639** [kiddkai/atom-node-debugger#77]
Is it possible to keep the break points in the code when the node process stops but the debug pane is still visible?

**Comment by codecontemplator** [comment]
When the debugged process exists the break points are losts. I guess it would not be too hard (but more than a simple fix) to keep track of the break points and try to activate them again when a new debug session is started but this functionallity is currently not there.

**Comment by codecontemplator** [comment]
Fixed in the latest version
