### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by gyzerok** [kiddkai/atom-node-debugger#80]
There is no contributions here since august.

I'm currently cannot get it working correctly with Atom 1.0.19 and node 4.1.1 on Mac OS X.

**Comment by codecontemplator** [comment]
What problemts do you have?

**Comment by gyzerok** [comment]
@codecontemplator I cannot set a breakpoint.

**Comment by codecontemplator** [comment]
Do you get anything in the log file? (Remember that currently breakpoints can only be set during an active debug session)

**Comment by codecontemplator** [comment]
@gyzerok could it be the same problem as #61 which indicates that on mac the breakpoints are not properly displayed? It seems from that report that the breakpoints are still set though. I do not currently have access to a mac to test this.

**Comment by gyzerok** [comment]
@codecontemplator Yes, probably its the same issue.
