### ISSUE TITLE
Collaborate with us

### ISSUE THREAD

**Issue by steelbrain** [kiddkai/atom-node-debugger#82]
I am the author of the linter package. We're thinking of writing a base debugging interface provider now. Your experience from this package will be very helpful. Would you mind sharing your ideas about how that base provider's API should look like and about it's UI?

**Comment by kiddkai** [comment]
Hey, thanks for interesting about this. I can't tell how the API will looks like, but basically it will have some common thing like ...

For the UI part

1. A repl
2. Gutter breakpoint management
3. Step in/out/continue
4. Function call stack
5. API for jump to a existing file
6. API for jump to not existing file(for the modules like http net 
7. Breakpoint UI
8. Debug process information

I guess that's what cross over my mind now. This will be tricky though...Maybe also need to provide some UI for profiling or heapdump stuff, or maybe not...

**Comment by steelbrain** [comment]
Thank you for your suggestion, it was definitely helpful. I'll try to carve out an API spec for that.
