### ISSUE TITLE
How to atom-node-debugger in ubuntu 

### ISSUE THREAD

**Issue by conan52** [kiddkai/atom-node-debugger#83]
Hello,
I'm new  with Nodejs and TypeScript. I want to use atom-node-debugger but I do not know how to use and i don't config it.
Can you write instruction in ubuntu 14.04? Thank you very much.

**Comment by codecontemplator** [comment]
@conan52 
I do not think that it should require much configuration. The nodePath might have to be set (it is defaulted to /bin/node on non windows os). 

In atom, choose file->open config. To add settings for node-debuger write something like:

```coffeescript
"*":
  "node-debugger":
    nodePath: "/path/to/node"
```

**Comment by conan52** [comment]
thank you @codecontemplator! 
It's working now. but i cant watch value. example var a= 2+3 i can't watch value of a. How to watch value of a?

**Comment by codecontemplator** [comment]
The locals view displays all the local variables and parameters in the current stack frame. The callstack view itself can be expanded to display variables in a selected stackframe. Moreover, the console can be used to evaluate expressions.

**Comment by uljdcwy** [comment]
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":50,"msg":"spawn { args: \n   [ '--debug-brk=5858',\n     '/home/ulj/Desktop/test/chineseQI/node.js' ],\n  env: null }","time":"2019-08-06T13:56:44.214Z","v":0}
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":30,"msg":"debugger start connect to process","time":"2019-08-06T13:56:44.231Z","v":0}
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":30,"msg":"debugger attempt to connect to child process","time":"2019-08-06T13:56:44.232Z","v":0}
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":50,"msg":"child_process ENOENT exit code. Message: spawn /bin/node ENOENT","time":"2019-08-06T13:56:44.240Z","v":0}
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":30,"msg":"child_process end out","time":"2019-08-06T13:56:44.242Z","v":0}
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":30,"msg":"child_process end error","time":"2019-08-06T13:56:44.243Z","v":0}
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":30,"msg":"child_process close","time":"2019-08-06T13:56:44.243Z","v":0}
{"name":"debugger","hostname":"ubuntu","pid":8900,"level":30,"msg":"client client closed","time":"2019-08-06T13:56:44.243Z","v":0}
