### ISSUE TITLE
Uncaught TypeError: Cannot read property 'functors' of undefined

### ISSUE THREAD

**Issue by jorgecuesta** [kiddkai/atom-node-debugger#94]
[Enter steps to reproduce below:]

1. debugging hapi.js on next to register hapi-redis plugin.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.1.9

### Stack Trace

Uncaught TypeError: Cannot read property 'functors' of undefined

```
At /Users/jorgecuesta/.atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/node_modules/raf/index.js:74

TypeError: Cannot read property 'functors' of undefined
  at TreeView.render (/Users/jorgecuesta/.atom/packages/node-debugger/lib/Components/TreeView.coffee:61:15)
  at Array.map (native)
  at Object.TreeView.defaultRender [as render] (/Users/jorgecuesta/.atom/packages/node-debugger/lib/Components/TreeView.coffee:70:51)
  at Function.TreeView.render (/Users/jorgecuesta/.atom/packages/node-debugger/lib/Components/TreeView.coffee:61:25)
  at Function.LocalsPane.render (/Users/jorgecuesta/.atom/packages/node-debugger/lib/Components/CallStackPane.coffee:152:14)
  at RightSidePane (/Users/jorgecuesta/.atom/packages/node-debugger/lib/Components/App.coffee:72:20)
  at App.render (/Users/jorgecuesta/.atom/packages/node-debugger/lib/Components/App.coffee:146:9)
  at redraw (/Users/jorgecuesta/.atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/index.js:65:23)
  at /Users/jorgecuesta/.atom/packages/node-debugger/node_modules/mercury/node_modules/main-loop/node_modules/raf/index.js:72:10

```

### Commands

```
     -3:22.1.0 core:paste (atom-text-editor.editor.is-focused)
  5x -3:03.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -3:01.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:52.6.0 node-debugger:stop (div.panel-body.padded.native-key-bindings)
     -2:51.2.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
     -2:33.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:24.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:24.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:23.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:20.2.0 node-debugger:stop (div.panel-body.padded.native-key-bindings)
     -2:19.1.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
  3x -1:49.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:43.4.0 node-debugger:stop (div.panel-body.padded.native-key-bindings)
     -1:42.5.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "node-debugger": {
    "nodePath": "/usr/local/bin/node"
  }
}
```

### Installed Packages

```coffee
# User
aligner-scss, v1.1.0
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.3
autocomplete-python, v0.9.4
color-picker, v2.0.13
csslint, v1.1.4
git-projects, v1.15.0
jsformat, v0.9.0
jslint, v1.4.0
linter, v1.10.0
node-debugger, v1.1.9
node-on-fire, v0.1.0
node-resolver, v1.0.1
nodejs-snippets, v1.0.3
react, v0.12.10
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
@jorgecuesta 
I looked at hapi.js (https://github.com/hapijs/hapi) and the hapi redis plugin (https://github.com/sandfox/node-hapi-redis) but I am not sure how to reproduce the problem.
I can see from the callstack that for some reason the stackframe fails to load in the locals view. I could fix the symptoms by adding a null check but I do not understand the circumstances when this happens.

**Comment by jorgecuesta** [comment]
Kiddkai it happen when try to stop on debugger statement placed inside of  function pass as callback to server.register invoked to add a plugin. hapi-redis to be more precise.

-----Mensaje original-----
De: "Daniel Brännström" <notifications@github.com>
Enviado el: ‎31/‎10/‎2015 04:04 p.m.
Para: "kiddkai/atom-node-debugger" <atom-node-debugger@noreply.github.com>
CC: "Jorge S. Cuesta" <jckpo2@gmail.com>
Asunto: Re: [atom-node-debugger] Uncaught TypeError: Cannot read property'functors' of undefined (#94)

@jorgecuesta 
I looked at hapi.js (https://github.com/hapijs/hapi) and the hapi redis plugin (https://github.com/sandfox/node-hapi-redis) but I am not sure how to reproduce the problem.
I can see from the callstack that for some reason the stackframe fails to load in the locals view. I could fix the symptoms by adding a null check but I do not understand the circumstances when this happens.

**Comment by codecontemplator** [comment]
Fixed in the latest version hopefully. Please report again if it does not help.
