### ISSUE TITLE
set Breakpoints

### ISSUE THREAD

**Issue by SerkanSipahi** [kiddkai/atom-node-debugger#96]
it is possible to set breakpoints? The debugger starts always from first line of code!

**Comment by 5punk** [comment]
You can set breakpoints by pressing F9 (Fn + F9 on Mac). I doubt you can set it via Clicking on the UI or on line number.

But the fact that the first line  of code is always a breakpoint and it resumes only when you click play is kind of annoying. I hope they fix it!

**Comment by SerkanSipahi** [comment]
Thank you i will try it

**Comment by codecontemplator** [comment]
Just to clarify: The reason that the debugger stops on the first line is to give the user the possiblity to set other breakpoints since currently breakpoints only lasts during the debugging session. (Not saying that this is ideal... just explaining the reason for the current behaviour :) )
