### ISSUE TITLE
Remote support

### ISSUE THREAD

**Issue by strarsis** [kiddkai/atom-node-debugger#99]
Is it possible to run node debug instance on a remote machine (like in a VM or container) 
and then connect to it from locally running atom?

As this package seems to connect to a node instance over TCP anyway, 
it seems to be easy to add a ip/host field (and optinally a ssh-launch command)?

Thank you and 
With best regards

**Comment by codecontemplator** [comment]
Hi,

It is currently not supported to connect to a remote process. See issue #23. It is a commonly requested feature though.
